### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by Shimwell** [Blitan/example_python_package_Blitan#1]
- [x] add test for my_name function
- [x] make github action to  run pytest automatically
- [x] register account with pypi
- [x] make github action to upload to pypi
- [x] make a development branch
- [x] add feature from development branch to main branch
